CREATE TABLE tbl_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    email VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(255),
    bio VARCHAR(100),
    profile_visibility VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_member_nickname UNIQUE (nickname),
    CONSTRAINT uq_member_email UNIQUE (email)
);

CREATE TABLE tbl_time_capsule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    content TEXT,
    time_capsule_type VARCHAR(20) NOT NULL,
    visibility VARCHAR(20) NOT NULL,
    lock_type VARCHAR(20) NOT NULL,
    password_hash VARCHAR(255),
    question VARCHAR(255),
    answer_hash VARCHAR(255),
    location GEOMETRY(Point, 4326) NOT NULL,
    location_name VARCHAR(255),
    open_radius_meter INTEGER NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    is_anonymous BOOLEAN NOT NULL,
    is_feed_public BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    CONSTRAINT fk_time_capsule_member FOREIGN KEY (member_id) REFERENCES tbl_member (id)
);

CREATE TABLE tbl_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_capsule_id BIGINT NOT NULL,
    media_type VARCHAR(20) NOT NULL,
    media_url VARCHAR(255) NOT NULL,
    s3_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_media_time_capsule FOREIGN KEY (time_capsule_id) REFERENCES tbl_time_capsule (id)
);

CREATE TABLE tbl_capsule_recipient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    time_capsule_id BIGINT NOT NULL,
    has_opened BOOLEAN NOT NULL,
    opened_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_capsule_recipient_member FOREIGN KEY (member_id) REFERENCES tbl_member (id),
    CONSTRAINT fk_capsule_recipient_time_capsule FOREIGN KEY (time_capsule_id) REFERENCES tbl_time_capsule (id),
    CONSTRAINT uq_capsule_recipient_time_capsule_member UNIQUE (time_capsule_id, member_id)
);

CREATE TABLE tbl_capsule_open (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_capsule_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    opened_at TIMESTAMP(6) NOT NULL,
    open_location GEOMETRY(Point, 4326),
    CONSTRAINT fk_capsule_open_time_capsule FOREIGN KEY (time_capsule_id) REFERENCES tbl_time_capsule (id),
    CONSTRAINT fk_capsule_open_member FOREIGN KEY (member_id) REFERENCES tbl_member (id),
    CONSTRAINT uq_capsule_open_time_capsule_member UNIQUE (time_capsule_id, member_id)
);

CREATE TABLE tbl_capsule_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_capsule_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_capsule_history_time_capsule FOREIGN KEY (time_capsule_id) REFERENCES tbl_time_capsule (id),
    CONSTRAINT fk_capsule_history_member FOREIGN KEY (member_id) REFERENCES tbl_member (id)
);

CREATE TABLE tbl_guestbook (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_capsule_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    CONSTRAINT fk_guestbook_time_capsule FOREIGN KEY (time_capsule_id) REFERENCES tbl_time_capsule (id),
    CONSTRAINT fk_guestbook_member FOREIGN KEY (member_id) REFERENCES tbl_member (id)
);

CREATE TABLE tbl_friend (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    accepted_at TIMESTAMP(6),
    CONSTRAINT fk_friend_requester FOREIGN KEY (requester_id) REFERENCES tbl_member (id),
    CONSTRAINT fk_friend_receiver FOREIGN KEY (receiver_id) REFERENCES tbl_member (id),
    CONSTRAINT uq_friend_requester_receiver UNIQUE (requester_id, receiver_id)
);

CREATE TABLE tbl_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    time_capsule_id BIGINT,
    notification_type VARCHAR(30) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_id) REFERENCES tbl_member (id),
    CONSTRAINT fk_notification_time_capsule FOREIGN KEY (time_capsule_id) REFERENCES tbl_time_capsule (id)
);

CREATE TABLE tbl_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    reason VARCHAR(30) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_report_reporter FOREIGN KEY (reporter_id) REFERENCES tbl_member (id),
    CONSTRAINT uq_report_reporter_target UNIQUE (reporter_id, target_type, target_id)
);

CREATE TABLE tbl_block (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id BIGINT NOT NULL,
    blocked_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_block_blocker FOREIGN KEY (blocker_id) REFERENCES tbl_member (id),
    CONSTRAINT fk_block_blocked FOREIGN KEY (blocked_id) REFERENCES tbl_member (id),
    CONSTRAINT uq_block_blocker_blocked UNIQUE (blocker_id, blocked_id)
);

CREATE INDEX idx_time_capsule_member ON tbl_time_capsule (member_id);
CREATE INDEX idx_time_capsule_visibility_deleted ON tbl_time_capsule (visibility, is_deleted);
CREATE INDEX idx_time_capsule_location ON tbl_time_capsule USING GIST (location);
CREATE INDEX idx_media_time_capsule ON tbl_media (time_capsule_id);
CREATE INDEX idx_capsule_recipient_member ON tbl_capsule_recipient (member_id);
CREATE INDEX idx_capsule_open_member ON tbl_capsule_open (member_id);
CREATE INDEX idx_capsule_history_time_capsule ON tbl_capsule_history (time_capsule_id);
CREATE INDEX idx_guestbook_time_capsule_deleted_created ON tbl_guestbook (time_capsule_id, is_deleted, created_at DESC);
CREATE INDEX idx_friend_receiver ON tbl_friend (receiver_id);
CREATE INDEX idx_notification_recipient_created ON tbl_notification (recipient_id, created_at DESC);
