-- Notification rows carry a spec-shaped (targetId, targetType) reference instead of a capsule-only FK:
-- FRIEND_REQUESTED / FRIEND_ACCEPTED point at a member or friend request, which time_capsule_id cannot
-- express. Renaming body -> content is safe without the usual two-phase dance because no code has ever
-- written to this table -- the domain had entities but no service until now, so there are no live writers
-- and no rows to migrate.
ALTER TABLE tbl_notification RENAME COLUMN body TO content;
ALTER TABLE tbl_notification ADD COLUMN target_id BIGINT;
ALTER TABLE tbl_notification ADD COLUMN target_type VARCHAR(30);

-- Phase 1 of the time_capsule_id removal: new code no longer maps the column and it is already nullable,
-- so a previous blue container can still write during a deployment. Drop it in a later migration.

-- Serves the isRead filter on the notification list endpoint; the existing
-- idx_notification_recipient_created only covers the unfiltered case.
CREATE INDEX idx_notification_recipient_read_created ON tbl_notification (recipient_id, is_read, created_at DESC);

CREATE TABLE tbl_device_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_device_token_member FOREIGN KEY (member_id) REFERENCES tbl_member (id),
    CONSTRAINT uq_device_token_token UNIQUE (token)
);

CREATE INDEX idx_device_token_member ON tbl_device_token (member_id);

-- The discovery feed reads tbl_capsule_open newest-first across every member, which the existing
-- idx_capsule_open_member (member-scoped) cannot serve.
CREATE INDEX idx_capsule_open_opened_at ON tbl_capsule_open (opened_at DESC);
