-- A-1 client-side encryption for locked capsules.
--
-- Capsules now come in two encryption modes and the column records which one a row uses, so the
-- open path can tell whether it may return a body at all rather than inferring it from lock_type:
--
--   SERVER_ENVELOPE - lock_type = NONE. The server holds the key and can read the body. This is
--                     inherent, not a shortcut: an unlocked capsule's only unlock condition is being at
--                     its coordinates, which the server knows, so it could always satisfy it itself.
--   CLIENT_E2E      - lock_type = PASSWORD or QUESTION. The client encrypts under a key the server never
--                     receives; the server stores an opaque blob and a sub-threshold set of key shares.
--
-- Existing rows predate client-side encryption, so they take the server-envelope default.
ALTER TABLE tbl_time_capsule
    ADD COLUMN encryption_mode VARCHAR(20) NOT NULL DEFAULT 'SERVER_ENVELOPE';

-- How many shares reconstruct the content key. Stored so the client knows how many to gather, and so the
-- server can check at creation time that the plaintext shares it was handed stay below this number.
-- Null for SERVER_ENVELOPE capsules, which have no shares.
ALTER TABLE tbl_time_capsule ADD COLUMN key_threshold INT;

CREATE TABLE tbl_key_share (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_capsule_id BIGINT NOT NULL,
    share_index INT NOT NULL,
    share_data TEXT NOT NULL,
    -- true when share_data is itself encrypted under a key derived from the capsule's password or answer.
    -- The server stores it but cannot unwrap it, which is what keeps it below the reconstruction
    -- threshold: without this share it holds fewer than `threshold` usable shares.
    is_wrapped BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_key_share_time_capsule FOREIGN KEY (time_capsule_id) REFERENCES tbl_time_capsule (id),
    CONSTRAINT uq_key_share_capsule_index UNIQUE (time_capsule_id, share_index)
);

CREATE INDEX idx_key_share_time_capsule ON tbl_key_share (time_capsule_id);
